# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('handicap', models.FloatField(default=20.0)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.IntegerField(default=1)),
                ('playersPerTeam', models.IntegerField(default=2)),
                ('rounds', models.IntegerField(default=2)),
                ('changeTeams', models.BooleanField(default=False)),
            ],
        ),
    ]
