# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfsetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(default='New Tournament', max_length=200),
        ),
    ]
